name: PythonOutput
on:
  push:
    branches: 
    - main
env:
  VIKI_VAR: ${{ vars.VIKI_VAR }}
  AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script 
        run: |
          python test.py
        env:
          key: ${{ secrets.key }} # if test.py requires passwords..etc, set it as secrets
      - name: some other step
        run: echo hello
        