name: PythonOutput
on:
  push:
    branches: 
    - main
env:
  VIKI_VAR: ${{ vars.VIKI_VAR }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10' #install the python needed
      - name: execute main script 
        run: |
          pip install requests
          python main.py      
      - name: execute py script 
        run: |
          python viki_azure_module.py
        env:
          key: ${{ secrets.key }} # if test.py requires passwords..etc, set it as secrets
      - name: some other step
        run: echo hello
        
